<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class LearnMore extends Unicore
{
    function init()
    {
        $this->uni('pe')->hook('main','learnMore')->output();
    }

}
