<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Home extends Unicore
{
    function init()
    {
        $this->uni('pe')
            ->addHead('title', 'PE')
            ->includeElement('overlay-slot')
            ->hook('main','home')
            ->output();
    }

}
