<?php
/* Generated by neoan3-cli */

namespace Neoan3\Frame;

use Neoan3\Apps\Template;
use Neoan3\Core\Serve;

class Pe extends Serve
{
    function __construct()
    {
        parent::__construct();
        $this->header = Template::embraceFromFile(
            'frame/pe/header.html',
            [
                'base' => base
            ]
        );
        $this->hook('footer', 'footer', []);
    }

    function constants()
    {
        return [
            'base' => [base],
            'meta' => [
                ['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1']
            ],
            'link' => [
                [
                    'sizes' => '32x32',
                    'type' => 'image/png',
                    'rel' => 'icon',
                    'href' => 'asset/favicon.png'
                ]
            ],
            'stylesheet' => [
                base . 'asset/projection/css/main.css',
                'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
                base . 'frame/pe/style.css',
            ]
        ];
    }
}
