<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Pe;

class NewsletterRegistration extends Pe
{


    function postNewsletterRegistration(array $body)
    {
        // TODO send over to sendgrid
        return $body;
    }

}
